// Result pattern — same as Nexo, proven pattern
export type Result<T, E = Error> = { ok: true; value: T } | { ok: false; error: E }

export function ok<T>(value: T): Result<T, never> {
  return { ok: true, value }
}

export function err<E>(error: E): Result<never, E> {
  return { ok: false, error }
}

// MCP Tool definition (simplified from MCP SDK)
export interface McpTool {
  name: string
  description: string
  inputSchema: Record<string, unknown>
  /** Compressed description (generated by Prism) */
  compressedDescription?: string
  /** Token count of the full schema */
  tokenCount?: number
  /** Which MCP server provides this tool */
  serverName: string
}

// MCP Server config
export interface McpServerConfig {
  name: string
  command: string
  args?: string[]
  env?: Record<string, string>
  /** Whether this server is enabled */
  enabled?: boolean
}

// Prism config
export interface PrismConfig {
  /** Max tokens for tool descriptions in context */
  maxTokenBudget: number
  /** MCP servers to proxy */
  servers: McpServerConfig[]
  /** Dashboard port */
  dashboardPort?: number
  /** SQLite path for traces */
  tracePath?: string
}

// Trace record
export interface TraceRecord {
  id: string
  sessionId: string
  serverName: string
  toolName: string
  input: Record<string, unknown>
  output: unknown
  startedAt: Date
  completedAt: Date
  durationMs: number
  inputTokens: number
  outputTokens: number
  error?: string
}

// Session summary
export interface SessionSummary {
  id: string
  startedAt: Date
  toolCalls: number
  totalTokens: number
  totalCostUsd: number
  errors: number
}
